language: node_js
node_js:
- '6'
before_install: npm i -g yarn
install: yarn install
script: yarn test
before_deploy: yarn build
deploy:
  provider: npm
  email: adamtalbot93@googlemail.com
  api_key:
    secure: Rc60MtrqmXf4pKF0L51lNX/Bgep736QSGJ4UpwTArTkT+vkhOdhmpqmUfRptcVF5iONtjfIjRDBWGMQBt7P6GuvhkKs0cRuJECVmM5Z+teJ4EpQ5T+5cpVXWZg9p7Xbk/ZWcsWe9ORwpmcYmIPwxE/XsJKxW9yOr4eh8nB31M1blArhN1zftzTjBlTqcltkAtuaYiuyHBYAdyTqVKIK0pEnqtp3VVj2/J9BWuyEiZSahF5G3hF11puj5YA2Y9jAxp775on1gFYn/YEiEToknhLjmO9l+qbVaIMqsH1ev+u3g2ju5cQcj4GItVElyXPBFPP4z+nNRV3itB+Iyeozq8BruJKQqOEmy1tD6x7EdNMxRxU+W4rDWWUqThaK5katvK8woLxzb2RUf2KMpUa/ZKdNX+/l1y3Kqol48dtqOc0UWpAssxVE7EvtROIiAzdP91MzsI9OCaIprCSadgYgpLDaSn+eI1eWAfNzcOQ9X2tE/cmFBRJgchM1JjqvH9QPGCcL6uMLqr4nQ6gvfelLVRONjx91RwUc1VzJkiny7fk249gY8QnRyiIeQugJeksVn8quxJ4kky/IBpkI+7VGDQ3yxT3pmxHrVi4IMNytv9PAkwr+XVA+0L4WkImiqqkhLbPF47DioZh12b1Iit5sjPEPoHBrDQhunqWoRbLsGOu0=
  on:
    tags: true
