language: node_js
node_js:
  - '6'

before_install: npm i -g yarn
install: yarn install
script: yarn test
before_deploy: yarn build

deploy:
  provider: npm
  email: adamtalbot93@googlemail.com
  api_key:
    secure: Xa8GOzIOzSkFPnwgC8t/siM6WbO50QssAqZCPHc6jLWFUDIFG/dacTutiGhsfmuLO9G0YRV3bxlxyLbKmWpVYnbjH1UUflZ9OJTOMLbV/9izHL4dvK8el0PMHLlkpPGirYLSkmcJ5CPUO4qsh0ylWedtKICxT4emC9HeULk24J45zVUUfaReK36HTyEcZJ6Sdq+4RP0pAZfO1PBC1FVu/thGxv5/mWDem/5X68pe8IAqUXIXD+CGImPABw9il4ABiNWNWNB6C6tQrHDI1N/lV/Wchzds/SNdVsiHxby7vGlqyF7p+xp5spZt6qzgUOQlyNmhKT3+1Ak9FsAqwPjQZ1SXcykM5iwdDFauaiMC2Ff/+3cCivg1wAX9qZ25WCWr2yu/xDfEPOLj4NkkjzT13Uc4OD2za4EpS/cYAthjqLAij9w3LJ/TrhXI0jT5a299ds3NQPprjr0/nhloc+Pf00UyA/BsFY2floSiBRkyCS2wgrIUdzfXN/UTPSNyb3OYYQuXzKEq0tXwBAet/gW70+YYTnNifXLsBmrqlMjBmxR9Yy5U/u21lR2Akv94MIrJ4bsj1SONK3hOjCvd5leUrFeWEYwy055fL9AinA3V/Sq5CPyLvlLSLA/WNABglsPac51+Q3jBuUTGJZfURmo9LeMUJd3QieiMPwQtJrYiUfg=
  on:
    tags: true
